<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://sped.rfb.gov.br/estatico/55/82C56BF5CACE455A34D679C36AD8DD350E243B/Pacote_XSD_Comunica%C3%A7%C3%A3o_EFD-REINF_v1.2_WSDL.wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="comunicaoreinf" targetNamespace="http://sped.rfb.gov.br/estatico/55/82C56BF5CACE455A34D679C36AD8DD350E243B/Pacote_XSD_Comunica%C3%A7%C3%A3o_EFD-REINF_v1.2_WSDL.wsdl">
  <wsdl:message name="NewOperationRequest">
    <wsdl:part name="NewOperationRequest" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="NewOperationResponse">
    <wsdl:part name="NewOperationResponse" type="xsd:string"/>
  </wsdl:message>
  <wsdl:portType name="comunicaoreinf">
    <wsdl:operation name="NewOperation">
      <wsdl:input message="tns:NewOperationRequest"/>
      <wsdl:output message="tns:NewOperationResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="comunicaoreinfHTTP" type="tns:comunicaoreinf">
    <http:binding verb="GET"/>
    <wsdl:operation name="NewOperation">
      <http:operation location="/NewOperation"/>
      <wsdl:input>
        <http:urlEncoded/>
      </wsdl:input>
      <wsdl:output>
        <mime:content type="text/xml"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="comunicaoreinf">
    <wsdl:port binding="tns:comunicaoreinfHTTP" name="comunicaoreinfHTTP">
      <http:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
